### ISSUE TITLE
Heroku Ping

### ISSUE THREAD

**Issue by nelsonic** [dwyl/ping#1]
At present the heroku app https://phxtodo.herokuapp.com takes _ages_ to boot when the person viewing the tutorial first clicks the link. "Ages" is not a scientific measure, but it _feels_ like forever and it reflects poorly on the App when in _reality_ Phoenix is _fast_ and initial load of the server-side rendered (and cached) Todo List is _much_ faster than any client-side implementation could ever be!

# Todo

+ [x] Borrow the code from our `email` app which has the same problem!
https://github.com/dwyl/email/blob/b4c2c4f4d96773c326cf3fa8cd4838973c9a78f5/lib/app_web/controllers/sent_controller.ex#L132-L147
+ [x] Make a _generic_ solution that can be implemented in _any_ of or projects that are deployed to Heroku
+ [ ] Implement it in the Todo List Tutorial to wake up the Heroku Dyno using a Pixel/GIF rendered in the `README.md`

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/83336993-aa65db80-a2af-11ea-9ade-bbaa05dba5da.png)

**Comment by nelsonic** [comment]
This is working on https://phoenix-content-negotiation.herokuapp.com/ping
PR: https://github.com/dwyl/phoenix-content-negotiation-tutorial/pull/5

**Comment by nelsonic** [comment]
remove surplus `/`:
![image](https://user-images.githubusercontent.com/194400/83339303-71843180-a2c4-11ea-8719-675c96121a8b.png)

**Comment by nelsonic** [comment]
PR: https://github.com/dwyl/phoenix-todo-list-tutorial/pull/39
